CREATE DATABASE IF NOT EXISTS WISHLISTS DEFAULT CHARACTER SET utf8;
USE WISHLISTS;
DROP TABLE if exists WISH;
DROP TABLE if exists COMPUTERPART;
DROP TABLE IF EXISTS SHARED_LIST;
DROP TABLE if exists WISHLIST;
DROP TABLE if exists USERR;

CREATE TABLE USERR (
uName VARCHAR(255) NOT NULL, 
userID INT PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE COMPUTERPART (
partID INT PRIMARY KEY AUTO_INCREMENT,
pName VARCHAR(255) UNIQUE NOT NULL ,
pPrice INT,
pType VARCHAR(255)
);

CREATE TABLE WISHLIST (
listID INT PRIMARY KEY AUTO_INCREMENT,
userID INT,
listName VARCHAR(255) NOT NULL,
totalPrice INT,
FOREIGN KEY (userID) REFERENCES USERR(userID)
);

CREATE TABLE WISH (
wishID INT PRIMARY KEY AUTO_INCREMENT,
partID INT NOT NULL,
numberCount INT,
listID int,
FOREIGN KEY (listID) REFERENCES WISHLIST(listID),
FOREIGN KEY (partID) REFERENCES COMPUTERPART(partID)
);

CREATE TABLE SHARED_LIST (
listID INT NOT NULL,
userID INT NOT NULL,
PRIMARY KEY(listID, userID),
FOREIGN KEY(listID) REFERENCES WISHLIST(listID),
FOREIGN KEY(userID) REFERENCES USERR(userID)
);

