CREATE DATABASE IF NOT EXISTS WISHLISTS DEFAULT CHARACTER SET utf8;
USE WISHLISTS;
DROP TABLE if exists WISH;
DROP TABLE if exists COMPUTERPART;
DROP TABLE IF EXISTS SHARED_LISTS;
DROP TABLE if exists WISHLIST;
DROP TABLE if exists USERR;

CREATE TABLE USERR (
uName VARCHAR(255) NOT NULL, 
sharedListID INT,
userID INT PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE COMPUTERPART (
partID INT PRIMARY KEY AUTO_INCREMENT,
pName VARCHAR(255) UNIQUE NOT NULL ,
pPrice INT,
pType VARCHAR(255)
);

CREATE TABLE WISHLIST (
listID INT PRIMARY KEY AUTO_INCREMENT,
userID INT,
wishID INT UNIQUE NOT NULL,
listName VARCHAR(255) NOT NULL,
totalPrice INT,
FOREIGN KEY (userID) REFERENCES USERR(userID)
);

CREATE TABLE WISH (
wishID INT PRIMARY KEY AUTO_INCREMENT,
partID INT NOT NULL,
numberCount INT,
FOREIGN KEY (wishID) REFERENCES WISHLIST(wishID),
FOREIGN KEY (partID) REFERENCES COMPUTERPART(partID)
);

CREATE TABLE SHARED_LISTS (
listID INT NOT NULL,
sharedToUserID INT NOT NULL,
PRIMARY KEY(listID, sharedToUserID),
FOREIGN KEY(listID) REFERENCES WISHLIST(listID),
FOREIGN KEY(sharedToUserID) REFERENCES USERR(userID)
);

